enabled: true
local_task_label: ''
fields:
  title:
    id: entity_label_clone_suffix
  body:
    id: copy_values
  field_contents:
    id: copy_values
  field_images:
    id: copy_values
  field_name:
    id: copy_values
